export const WIDTH = 640
export const HEIGHT = 480
export const COL_1_KEY = 'd'
export const COL_2_KEY = 'f'
export const COL_3_KEY = 'j'
export const COL_4_KEY = 'k'
export const CURSOR_LEFT_KEY = 'ArrowLeft'
export const CURSOR_RIGHT_KEY = 'ArrowRight'
export const COL_WIDTH = 50
export const HOLD_WIDTH = 30
export const NOTE_HEIGHT = 10
export const PLAYFIELD_WIDTH = COL_WIDTH * 4
export const SCROLL_SPEED = 100 // px per sec
export const NOTE_TRAVEL_DURATION = (HEIGHT / SCROLL_SPEED) * 1000
